%YAML:1.0

# output directory
output_dir: "~/larvio_results/"

# switches
# switches
if_FEJ: 1    # 0(false) or 1(true)
estimate_extrin: 1    # 0(false) or 1(true)
estimate_td: 0    # 0(false) or 1(true)
calib_imu_instrinsic: 0    # 0(false) or 1(true)

# camera instrinsic
camera_model: "pinhole"       # only support "pinhole"
distortion_model: "radtan"    # only support "radtan" and "equidistant"
resolution_width: 640
resolution_height: 480
intrinsics:
   fx: 385.94651107381173
   fy: 386.80952391929685
   cx: 317.6384942676234
   cy: 238.35352398894932
distortion_coeffs:
   k1: 0.008102965627466683
   k2: -0.0055070179614814625
   p1: -0.001060696563532148
   p2: -0.0005589807711704417

# imu-camera extrinsic, including spacial and temporal parameters
T_cam_imu: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data:
    [0.99999678, 0.00198932,  -0.00157488, -0.00444001,
    -0.00198420, 0.99999277, 0.00324455, 0.00045296,
     0.00158133, -0.00324141, 0.99999350, 0.01333104,
                     0,                   0,                   0,   1.000000000000000]
td: 0.0041313985533080605  

#td: 0.0
# TODO: if calibrate camera instrinsic online

# visual front-end parameters
# visual front-end parameters
pyramid_levels: 2
patch_size: 21
fast_threshold: 30
max_iteration: 30
track_precision: 0.01
ransac_threshold: 1
max_features_num: 300
min_distance: 15
flag_equalize: 0    # 0(false) or 1(true)
pub_frequency: 20


# window size
sw_size: 20

# online reset thresholds
position_std_threshold: 8.0
rotation_threshold: 0.2618
translation_threshold: 0.4
tracking_rate_threshold: 0.5

# feature triangulation parameters
least_observation_number: 3
max_track_len: 6
feature_translation_threshold: -1.0

# imu and camera measurement noise parameters
noise_gyro: 2.8720118786860445e-02
noise_acc:  1.8579866117590046e-01
noise_gyro_bias: 1.8149405667931398e-05
noise_acc_bias: 2.7757851353564139e-02
noise_feature: 0.008

#noise_gyro: 0.01
#noise_acc: 0.1
#noise_gyro_bias: 2e-5
#noise_acc_bias: 4e-4
#noise_feature: 0.008

# filter intial covariance
initial_covariance_orientation: 4e-4
initial_covariance_velocity: 0.25
initial_covariance_position: 0.0
initial_covariance_gyro_bias: 4e-4
initial_covariance_acc_bias: 0.01
initial_covariance_extrin_rot: 3.0462e-8
initial_covariance_extrin_trans: 9e-8

# fej settings
reset_fej_threshold: 10.11

# zupt settings
if_ZUPT_valid: 1    # 0(false) or 1(true)
zupt_max_feature_dis: 2e-3
zupt_noise_v: 1e-2    # std
zupt_noise_p: 1e-2
zupt_noise_q: 3.4e-2

# static initialization setting
static_duration: 3.0

# measurement rate
imu_rate: 200
img_rate: 15

# augmented feature state settings
max_features_in_one_grid: 1     # pure msckf if set to 0
aug_grid_rows: 5
aug_grid_cols: 7
feature_idp_dim: 1              # 1 or 3

# if apply Schmidt filter
use_schmidt: 0    # 0(false) or 1(true)
